#!/bin/bash
# ==========================================
# 🧠 Sing-box IPv4 TProxy 一键配置脚本 (增强版)
# 
# 作者: shangkouyou Duang Scu
# 优化: Antigravity
# 版本: v1.6 (Strict Interface Binding & Docker Fix)
#
# 更新日志:
# - v1.6: 
#   - 强制绑定 LAN 接口，防止宿主机流量回环
#   - 明确豁免 Docker 默认网段 (172.16.0.0/12 等)
#   - 优化依赖检查和错误处理
# ==========================================

# 检查 bash 环境
if [ -z "$BASH_VERSION" ]; then
    echo "⚠️  此脚本需要 bash 环境。正在尝试切换..."
    exec bash "$0" "$@"
fi

set -e
LOG_FILE="/var/log/tproxy-setup.log"
TPROXY_DIR="/etc/tproxy"
TPROXY_SCRIPT="$TPROXY_DIR/tproxy.sh"
TPROXY_PORT=9420
# 默认 mark 值
TPROXY_MARK=0x2333
TABLE_ID=100
DOCKER_PORT=9277
CUSTOM_CHAIN="TPROXY_CHAIN"

# --- 辅助函数 ---
log() {
    echo "[$(date '+%F %T')] $1" | tee -a "$LOG_FILE"
}

# 检测 Mihomo routing-mark
detect_mihomo_routing_mark() {
    local mihomo_config="/etc/mihomo/config.yaml"
    if [ -f "$mihomo_config" ]; then
        local routing_mark=$(grep -E "^routing-mark:" "$mihomo_config" 2>/dev/null | awk '{print $2}' | tr -d ' ' | head -n1)
        if [ -n "$routing_mark" ] && [[ "$routing_mark" =~ ^[0-9]+$ ]]; then
            printf "0x%X" "$routing_mark" 2>/dev/null
            return 0
        fi
    fi
    echo "0x2333"
}

# 检测主网卡 (LAN 接口)
detect_lan_interface() {
    # 优先检测默认路由接口
    local iface=$(ip -4 route show default 2>/dev/null | grep -o 'dev [^ ]*' | awk '{print $2}' | head -n1)
    if [ -z "$iface" ]; then
        # 备用：检测非 lo 的第一个接口
        iface=$(ip -4 link show | grep -E '^[0-9]+:' | grep -v 'lo:' | head -n1 | awk -F': ' '{print $2}' | awk '{print $1}')
    fi
    echo "$iface"
}

# --- 主逻辑 ---

log "🚀 开始配置 IPv4 TProxy 环境 (v1.6)..."

# 1. 环境准备
mkdir -p "$TPROXY_DIR"

# 检查并安装依赖
MISSING_PKGS=()
for cmd in iptables ip netstat; do
    if ! command -v $cmd > /dev/null 2>&1; then
        case $cmd in
            iptables) MISSING_PKGS+=("iptables") ;;
            ip) MISSING_PKGS+=("iproute2") ;;
            netstat) MISSING_PKGS+=("net-tools") ;;
        esac
    fi
done

if [ ${#MISSING_PKGS[@]} -gt 0 ]; then
    log "📦 安装缺失依赖: ${MISSING_PKGS[*]}"
    if [ -f /etc/alpine-release ]; then
        apk update && apk add "${MISSING_PKGS[@]}"
    elif [ -f /etc/debian_version ]; then
        apt-get update && apt-get install -y "${MISSING_PKGS[@]}"
    elif [ -f /etc/redhat-release ]; then
        yum install -y "${MISSING_PKGS[@]}"
    fi
fi

# 2. 内核模块和参数
for mod in xt_TPROXY nf_tproxy_ipv4; do
    modprobe $mod 2>/dev/null || true
done

sysctl -w net.ipv4.ip_forward=1 > /dev/null
if ! grep -q '^net.ipv4.ip_forward' /etc/sysctl.conf 2>/dev/null; then
    echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
fi

# 3. 同步 Mark
DETECTED_MARK=$(detect_mihomo_routing_mark)
if [ "$DETECTED_MARK" != "$TPROXY_MARK" ]; then
    TPROXY_MARK="$DETECTED_MARK"
    log "✅ 同步 Mihomo routing-mark: $TPROXY_MARK"
fi

# 4. 生成 TProxy 脚本
cat > "$TPROXY_SCRIPT" <<EOF
#!/bin/bash
# IPv4 TProxy Script (Generated by setup-tproxy-ipv4.sh v1.6)

LOG_FILE="/var/log/tproxy.log"
TPROXY_PORT=$TPROXY_PORT
TPROXY_MARK=$TPROXY_MARK
TABLE_ID=$TABLE_ID
DOCKER_PORT=$DOCKER_PORT
CHAIN_NAME="$CUSTOM_CHAIN"

log() {
    echo "[\$(date '+%F %T')] \$1" | tee -a "\$LOG_FILE"
}

wait_for_mihomo() {
    local max_wait=60
    local waited=0
    log "⏳ 等待 Mihomo 启动..."
    while [ \$waited -lt \$max_wait ]; do
        if netstat -tuln 2>/dev/null | grep -q ":\$TPROXY_PORT "; then
            log "✅ Mihomo 已就绪"
            return 0
        fi
        sleep 2
        waited=\$((waited + 2))
    done
    log "❌ 等待 Mihomo 超时"
    return 1
}

# --- 核心逻辑 ---

log "🚀 启动 TProxy 配置..."

if ! wait_for_mihomo; then
    exit 1
fi

# 自动检测 LAN 接口
LAN_IF="\$(ip -4 route show default 2>/dev/null | grep -o 'dev [^ ]*' | awk '{print \$2}' | head -n1)"
[ -z "\$LAN_IF" ] && LAN_IF="\$(ip -4 link show | grep -E '^[0-9]+:' | grep -v 'lo:' | head -n1 | awk -F': ' '{print \$2}' | awk '{print \$1}')"

log "ℹ️  LAN 接口: \$LAN_IF"

# 获取本机 IP 用于豁免
MAIN_IP="\$(ip -4 addr show "\$LAN_IF" 2>/dev/null | grep 'inet ' | awk '{print \$2}' | cut -d/ -f1 | head -n1)"

# 清理旧规则
iptables -t mangle -D PREROUTING -i "\$LAN_IF" -j \$CHAIN_NAME 2>/dev/null || true
iptables -t mangle -D PREROUTING -j \$CHAIN_NAME 2>/dev/null || true
iptables -t mangle -F \$CHAIN_NAME 2>/dev/null || true
iptables -t mangle -X \$CHAIN_NAME 2>/dev/null || true
ip rule del fwmark \$TPROXY_MARK table \$TABLE_ID 2>/dev/null || true
ip route flush table \$TABLE_ID 2>/dev/null || true

# 创建新链
iptables -t mangle -N \$CHAIN_NAME

# rule 1: 豁免本机和广播
iptables -t mangle -A \$CHAIN_NAME -d 127.0.0.0/8 -j RETURN
iptables -t mangle -A \$CHAIN_NAME -d 255.255.255.255 -j RETURN
if [ -n "\$MAIN_IP" ]; then
    iptables -t mangle -A \$CHAIN_NAME -d "\$MAIN_IP" -j RETURN
    iptables -t mangle -A \$CHAIN_NAME -s "\$MAIN_IP" -j RETURN
fi

# rule 2: 豁免局域网私有段 (LAN互访)
iptables -t mangle -A \$CHAIN_NAME -d 10.0.0.0/8 -j RETURN
iptables -t mangle -A \$CHAIN_NAME -d 172.16.0.0/12 -j RETURN
iptables -t mangle -A \$CHAIN_NAME -d 192.168.0.0/16 -j RETURN

# rule 3: 豁免 Docker 网段 (关键：防止容器流量被误劫持)
# 默认 Docker 网桥通常是 172.17.0.0/16，已包含在 172.16.0.0/12 中
# 如果有其他自定义网段，请在此添加

# rule 4: 豁免特定端口
iptables -t mangle -A \$CHAIN_NAME -p tcp --dport \$DOCKER_PORT -j RETURN
iptables -t mangle -A \$CHAIN_NAME -p udp --dport \$DOCKER_PORT -j RETURN

# rule 5: UDP 443 QUIC 阻断 (强制回落 TCP)
iptables -t mangle -A \$CHAIN_NAME -p udp --dport 443 -j DROP

# rule 6: TProxy 转发
iptables -t mangle -A \$CHAIN_NAME -p tcp -j TPROXY --on-port \$TPROXY_PORT --tproxy-mark \$TPROXY_MARK
iptables -t mangle -A \$CHAIN_NAME -p udp -j TPROXY --on-port \$TPROXY_PORT --tproxy-mark \$TPROXY_MARK

# 挂载到 PREROUTING (仅针对 LAN 接口入站流量)
# 这是 "网关模式" 的核心：只处理进入 LAN 口的流量，不处理本机发出的流量(OUTPUT)
if [ -n "\$LAN_IF" ]; then
    iptables -t mangle -I PREROUTING -i "\$LAN_IF" -j \$CHAIN_NAME
    log "✅ 已将 TProxy 挂载到接口 \$LAN_IF"
else
    # 无法检测接口时回退到全局 (不推荐，但作为保底)
    iptables -t mangle -I PREROUTING -j \$CHAIN_NAME
    log "⚠️  未检测到 LAN 接口，挂载到全局 PREROUTING"
fi

# 策略路由 (处理被 TProxy 标记的流量)
ip rule add fwmark \$TPROXY_MARK table \$TABLE_ID
ip route add local default dev lo table \$TABLE_ID

log "✅ IPv4 TProxy 配置完成"
EOF

chmod +x "$TPROXY_SCRIPT"

# 5. 创建系统服务

# 检测系统类型生成服务文件
if [ -f /etc/alpine-release ]; then
    # Alpine OpenRC
    cat > /etc/init.d/tproxy <<EOFRC
#!/sbin/openrc-run
description="Sing-box IPv4 TProxy Service"
command="$TPROXY_SCRIPT"
command_background="yes"
pidfile="/run/tproxy.pid"

depend() {
    need net mihomo
    after firewall
}

start() {
    ebegin "Starting TProxy"
    \$command
    eend \$?
}

stop() {
    ebegin "Stopping TProxy"
    iptables -t mangle -F $CUSTOM_CHAIN 2>/dev/null
    iptables -t mangle -D PREROUTING -j $CUSTOM_CHAIN 2>/dev/null
    # 注意：如果指定了接口，还需要清理带接口参数的规则，这里简单处理
    # 实际上脚本重新运行时会清理
    eend 0
}
EOFRC
    chmod +x /etc/init.d/tproxy
    rc-update add tproxy default
    rc-service tproxy restart
else
    # Systemd
    cat > /etc/systemd/system/tproxy.service <<EOFSD
[Unit]
Description=Sing-box IPv4 TProxy Service
After=network.target mihomo.service
Requires=mihomo.service

[Service]
Type=oneshot
ExecStart=$TPROXY_SCRIPT
RemainAfterExit=yes
ExecStop=/usr/bin/iptables -t mangle -F $CUSTOM_CHAIN
ExecStop=/usr/bin/ip rule del fwmark $TPROXY_MARK table $TABLE_ID

[Install]
WantedBy=multi-user.target
EOFSD
    systemctl daemon-reload
    systemctl enable tproxy
    systemctl restart tproxy
fi

log "🎉 TProxy 安装并启动成功！"
log "   客户端网关请指向本机 IP"
